gui:
  nerdFontsVersion: "3"
customCommands:
  - key: "C"
    command: "git cz"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "0"
    command: "generate_commit_msg"
    context: "files"
    loadingText: "Generate commit messages"
    subprocess: true
