require("weidinger.UI.toggleterm")
require("weidinger.UI.lualine")
require("weidinger.UI.telescope")
require("weidinger.UI.tree")
require("weidinger.UI.trouble")
require("weidinger.UI.whichkey")
require("weidinger.UI.harpoon")
